name: msCI

env:
  COMMIT_MSG: ${{ github.event.head_commit.message }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches:
      - main
    paths-ignore: 
      - .github/workflows/ci.yml
  pull_request:
    branches:
      - main
    types:
      - opened
    paths-ignore: 
      - .github/workflows/ci.yml

jobs:
  build_and_publish_release:

    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven - Code quality & security
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Obligatorio-ORT-FI-8184-DevOps_${{ env.REPOSITORY_NAME }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Run with Java
      run: java -jar /home/runner/work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/target/ms-build.jar --server.port=8080 &

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install Newman & Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run postman collection & report
      run: |
        mkdir -p testResults
        newman run .github/tests/${{ env.REPOSITORY_NAME }}.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/testReport.html

    - name: Error msg
      if: failure()
      run: echo "NE=with failure " >> $GITHUB_ENV
      
    - name: Upload report artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.REPOSITORY_NAME }}-TestReport
        path: testResults/testReport.html
        retention-days: 5

    - name: Send telegram message
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: testResults/testReport.html
        message: |
          << CI pipeline - Monolith Tests completed ${{ env.NE }}>>
          Trigger user: ${{ github.actor }}
          Commit message: ${{ env.COMMIT_MSG }}
          Changes:
          https://github.com/Obligatorio-ORT-FI-8184-DevOps/${{ env.REPOSITORY_NAME }}/commit/${{github.sha}}
          Code quality & security:
          https://sonarcloud.io/summary/overall?id=Obligatorio-ORT-FI-8184-DevOps_${{ env.REPOSITORY_NAME }}
          Run log and test report:
          https://github.com/Obligatorio-ORT-FI-8184-DevOps/${{ env.REPOSITORY_NAME }}/actions/runs/${{ github.run_id }}

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: /home/runner/work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/target/ms-build.jar
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: "ReleaseInfo.md"
        generateReleaseNotes: true
        tag: ${{ env.COMMIT_MSG }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_PAT }}
        repository: Obligatorio-ORT-FI-8184-DevOps/DevOps_code
        event-type: ${{ env.COMMIT_MSG }}
        client-payload: '{"tag": "${{ env.COMMIT_MSG }}", "repo": "${{ env.REPOSITORY_NAME }}"}'